export const VERSION_MARKER = 'crewdoku-domain'

export * from './ids'
export * from './entities/types'
export * from './entities/factories'
export * from './calendar/calendar'
export * from './schedule/schedule'
export * from './schedule/dto'
export * from './constraints/context'
export * from './constraints/hard'
export * from './constraints/soft'
export * from './constraints/registry'
export * from './export/csv'
export * from './ports/ports'
export * from './solver/model'
export * from './solver/score'
export * from './solver/mapSolution'
export * from './solver/proposal'
export * from './solver/conflict'
export * from './seed/demo'
