/* Crewdoku app shell v0.1.0
   Offline-first, single-user scheduling tool. One planner, no roles, no approvals.
   All state lives in the browser (IndexedDB). Network not required. */
const { useState, useEffect, useReducer, useMemo, useRef } = React;

/* ================================================================
   EXPORT HELPERS
================================================================ */
const _m = (n, m) => ((n % m) + m) % m;

function _dlCSV(csv, filename) {
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(a.href), 1000);
}

function _buildCSV(rows) {
  return rows.map(r => r.map(v => '"' + String(v).replace(/"/g, '""') + '"').join(",")).join("\n");
}

function exportTeamCSV(overrides, weekOffset) {
  const days = Array.from({ length: 7 }, (_, k) => weekOffset * 7 + k);
  const rows = [["Name","ID","Department","Date","Day","Shift","Code","Start","End","Hours"]];
  SF.EMPLOYEES.forEach(emp => {
    days.forEach(d => {
      if (!SF.inHorizon(d)) return;
      const o    = overrides.get(emp.i + "|" + d);
      const code = o !== undefined ? o.code : SF.baseAssign(emp.i, d);
      if (code === undefined) return;
      const s  = code ? SF.SHIFTS.find(x => x.code === code) : null;
      const dt = SF.dateOf(d);
      const ds = dt.getFullYear() + "-" + String(dt.getMonth()+1).padStart(2,"0") + "-" + String(dt.getDate()).padStart(2,"0");
      rows.push([emp.name, emp.id, emp.deptName, ds, SF.DOW[_m(d,7)],
        s ? s.name : "Day off", code || "",
        s ? SF.hh(s.start) : "", s ? SF.hh(s.end) : "", s ? s.end - s.start : 0]);
    });
  });
  _dlCSV(_buildCSV(rows), "crewdoku-team-week" + weekOffset + ".csv");
}

function exportPersonCSV(empIdx, overrides) {
  const emp = SF.EMPLOYEES[empIdx];
  if (!emp) return;
  const days = Array.from({ length: 28 }, (_, k) => k - 14);
  const rows = [["Name","Date","Day","Shift","Code","Start","End","Hours"]];
  days.forEach(d => {
    if (!SF.inHorizon(d)) return;
    const o    = overrides.get(empIdx + "|" + d);
    const code = o !== undefined ? o.code : SF.baseAssign(empIdx, d);
    if (code === undefined) return;
    const s  = code ? SF.SHIFTS.find(x => x.code === code) : null;
    const dt = SF.dateOf(d);
    const ds = dt.getFullYear() + "-" + String(dt.getMonth()+1).padStart(2,"0") + "-" + String(dt.getDate()).padStart(2,"0");
    rows.push([emp.name, ds, SF.DOW[_m(d,7)], s ? s.name : "Day off", code || "",
      s ? SF.hh(s.start) : "", s ? SF.hh(s.end) : "", s ? s.end - s.start : 0]);
  });
  _dlCSV(_buildCSV(rows), "crewdoku-" + emp.name.replace(/\s+/g,"-").toLowerCase() + ".csv");
}

function printSchedule(overrides, weekOffset, empIdx) {
  const isSingle = empIdx != null;
  const emps     = isSingle ? [SF.EMPLOYEES[empIdx]] : SF.EMPLOYEES;
  const days     = Array.from({ length: 7 }, (_, k) => weekOffset * 7 + k);
  const weekStart = SF.dateOf(days[0]).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
  const SC = { N:"#c7d7f5", E:"#b8e8d8", M:"#d8ebb8", A:"#eed8b0", L:"#ecc0c0" };

  const rows = emps.map(emp => {
    const cells = days.map(d => {
      const o    = overrides.get(emp.i + "|" + d);
      const code = o !== undefined ? o.code : SF.baseAssign(emp.i, d);
      if (code === undefined) return `<td style="color:#bbb;text-align:center">–</td>`;
      if (!code) return `<td style="color:#aaa;text-align:center;font-size:7px">OFF</td>`;
      const s = SF.SHIFTS.find(x => x.code === code);
      return `<td style="background:${SC[code]||"#eee"};text-align:center;font-weight:600">${code}<br><span style="font-weight:400;font-size:7px;opacity:.75">${SF.hh(s.start)}-${SF.hh(s.end)}</span></td>`;
    }).join("");
    return `<tr><td style="white-space:nowrap;padding-right:8px;font-weight:500">${emp.name}</td><td style="color:#888;padding-right:8px;font-size:8px;white-space:nowrap">${emp.deptName}</td>${cells}</tr>`;
  }).join("");

  const html = `<!DOCTYPE html><html><head><title>Schedule · ${weekStart}</title>
    <style>
      *{box-sizing:border-box}body{font-family:"IBM Plex Sans",sans-serif;font-size:9px;color:#111;margin:0;padding:14px}
      h1{font-size:13px;font-weight:700;margin:0 0 3px}p{font-size:8px;color:#777;margin:0 0 10px}
      table{border-collapse:collapse;width:100%;table-layout:fixed}
      th,td{border:1px solid #e4e4e4;padding:3px 4px}th{background:#f6f6f6;font-weight:600;text-align:center}
      @page{size:A4 landscape;margin:8mm}
    </style></head><body>
    <h1>${isSingle ? SF.EMPLOYEES[empIdx].name + " — Personal schedule" : "Team schedule"}</h1>
    <p>Week of ${weekStart} · Generated by Crewdoku · ${new Date().toLocaleDateString("en-US")}</p>
    <table><thead><tr>
      <th style="width:130px;text-align:left">Name</th>
      <th style="width:90px;text-align:left">Department</th>
      ${days.map(d => `<th>${SF.DOW[_m(d,7)]}<br>${SF.dateOf(d).getDate()}</th>`).join("")}
    </tr></thead><tbody>${rows}</tbody></table>
  </body></html>`;

  const win = window.open("", "_blank");
  if (!win) { alert("Please allow popups to print / save as PDF"); return; }
  win.document.write(html);
  win.document.close();
  win.onload = () => { win.focus(); win.print(); };
}

/* ================================================================
   STATE — single planner, no roles
================================================================ */
const initialState = {
  adminView:    "board",
  adminSection: "shifts",
  weekOffset:   0,
  seedMode:     false,
  pins:         new Set(),
  overrides:    new Map(),
  diff:         null,
  dataMode:     "empty",  // "empty" | "demo" | "custom"
  locale:       "en",
  dbLoaded:     false,
};

function reducer(state, a) {
  switch (a.type) {
    case "ADMIN_VIEW":    return { ...state, adminView: a.view };
    case "ADMIN_SECTION": return { ...state, adminSection: a.section };
    case "WEEK":
      return { ...state, weekOffset: a.set !== undefined ? a.set : state.weekOffset + a.delta };
    case "SEED_TOGGLE":   return { ...state, seedMode: !state.seedMode };
    case "SEED_OFF":      return { ...state, seedMode: false };
    case "PIN_TOGGLE": {
      const pins = new Set(state.pins);
      pins.has(a.key) ? pins.delete(a.key) : pins.add(a.key);
      return { ...state, pins };
    }
    case "SET_CELL": {
      const overrides = new Map(state.overrides);
      overrides.set(a.key, { code: a.code, viol: a.viol || [] });
      return { ...state, overrides };
    }
    case "MOVE_CELL": {
      const overrides = new Map(state.overrides);
      overrides.set(a.src.key, { code: a.src.code, viol: a.src.viol || [] });
      overrides.set(a.dst.key, { code: a.dst.code, viol: a.dst.viol || [] });
      return { ...state, overrides };
    }
    case "SET_PROPOSAL":  return { ...state, diff: { proposal: a.proposal, decided: new Map() } };
    case "DIFF_DECIDE": {
      const decided = new Map(state.diff.decided);
      a.decision ? decided.set(a.key, a.decision) : decided.delete(a.key);
      return { ...state, diff: { ...state.diff, decided } };
    }
    case "DIFF_ALL": {
      const decided = new Map();
      state.diff.proposal.changes.forEach(c => decided.set(c.key, a.decision));
      return { ...state, diff: { ...state.diff, decided } };
    }
    case "DIFF_APPLY": {
      const overrides = new Map(state.overrides);
      state.diff.proposal.changes.forEach(c => {
        if (state.diff.decided.get(c.key) === "accept")
          overrides.set(c.key, { code: c.to, viol: [] });
      });
      return { ...state, overrides, diff: null };
    }
    case "DIFF_DISCARD": return { ...state, diff: null };
    case "CLEAR_EDITS":  return { ...state, overrides: new Map() };
    case "UNPIN_ALL":    return { ...state, pins: new Set() };
    case "LOAD_DEMO":    return {
      ...state,
      dataMode:  "demo",
      pins:      new Set(),
      overrides: new Map(),
      diff:      null,
    };
    case "LOAD_CUSTOM":  return {
      ...state,
      dataMode:  "custom",
      pins:      new Set(),
      overrides: new Map(),
      diff:      null,
    };
    case "RESET":        return {
      ...initialState,
      dbLoaded: true,
      locale:   state.locale,
    };
    case "SET_LOCALE":   return { ...state, locale: a.locale };
    case "DB_LOAD":      return {
      ...state,
      dataMode:  a.data.dataMode  || state.dataMode,
      locale:    a.data.locale    || state.locale,
      overrides: a.data.overrides ? DB.objToMap(a.data.overrides) : state.overrides,
      dbLoaded:  true,
    };
    default: return state;
  }
}

/* ================================================================
   EMPTY BOARD STATE
================================================================ */
function EmptyBoardState({ dispatch, onSetupOrg }) {
  return (
    <div className="flex-1 flex flex-col items-center justify-center gap-5 p-8 select-none"
      data-screen-label="Empty board">
      <div className="w-12 h-12 border-2 border-dashed rounded-[2px] flex items-center justify-center"
        style={{ borderColor: "var(--border)" }}>
        <span className="font-mono text-xl" style={{ color: "var(--text-faint)" }}>▦</span>
      </div>
      <div className="text-center space-y-1.5 max-w-xs">
        <h2 className="text-sm font-semibold">No schedule loaded</h2>
        <p className="text-xs leading-relaxed" style={{ color: "var(--text-dim)" }}>
          Set up your organisation to get started. The wizard takes about 3 minutes.
        </p>
      </div>
      <Btn variant="primary" size="lg" onClick={onSetupOrg}>
        Set up your organisation →
      </Btn>
    </div>
  );
}

/* ================================================================
   SIDEBAR
================================================================ */
function SideLabel({ children }) {
  return (
    <p className="px-3 pt-3 pb-1 text-2xs font-semibold uppercase tracking-widest text-faint first:pt-2">
      {children}
    </p>
  );
}

function NavItem({ icon, label, badge, active, disabled, onClick }) {
  return (
    <button type="button" onClick={onClick} disabled={disabled}
      title={disabled ? "Complete setup first" : undefined}
      className={cx(
        "w-full flex items-center gap-2 px-3 h-7 text-xs rounded-[2px] text-left transition-none",
        disabled ? "opacity-35 cursor-not-allowed" :
        active
          ? "bg-[var(--sel-bg)] text-ink font-semibold"
          : "text-dim hover:bg-surface-2 hover:text-ink"
      )}>
      <span className="font-mono text-xs w-3.5 text-center shrink-0 opacity-60">{icon}</span>
      <span className="flex-1 truncate">{label}</span>
      {badge > 0 && <Badge tone="warn" className="ml-auto">{badge}</Badge>}
    </button>
  );
}

const LOCALE_OPTIONS = [
  { v: "en", label: "English" },
  { v: "vi", label: "Tiếng Việt" },
];

function Sidebar({ app, dispatch, isDataLoaded }) {
  const hasDiff = !!app.diff;

  const CONFIG_SECTIONS = [
    { v: "shifts",  icon: "≡", label: "Shift definitions"   },
    { v: "rules",   icon: "§", label: "Scheduling rules"    },
    { v: "teams",   icon: "◫", label: "Teams & structure"   },
    { v: "prefs",   icon: "◈", label: "Emp. preferences"    },
    { v: "weights", icon: "≈", label: "Schedule priorities" },
  ];

  return (
    <aside className="w-48 shrink-0 border-r border-bd bg-surface flex flex-col select-none overflow-hidden">

      {/* brand */}
      <div className="h-9 flex items-center gap-2 px-3 border-b border-bd shrink-0">
        <img src="assets/logo.svg" width="20" height="20" alt="Crewdoku" style={{ display: "block" }} />
        <span className="text-xs font-semibold">Crewdoku</span>
        <span className="flex-1"></span>
        <span className="font-mono text-2xs px-1 border border-bd rounded-[2px] text-faint">v0.1.0</span>
      </div>

      {/* nav */}
      <nav className="flex-1 overflow-auto px-1.5 pb-2">
        <SideLabel>Schedule</SideLabel>
        <NavItem icon="▦" label="Board"
          active={app.adminView === "board" || app.adminView === "generate"}
          onClick={() => dispatch({ type: "ADMIN_VIEW", view: "board" })} />

        {hasDiff && (
          <div className="mx-1.5 mt-1 px-2 py-1.5 border rounded-[2px] text-2xs leading-snug cursor-pointer"
            style={{ background: "var(--st-prop-bg)", borderColor: "var(--st-prop)", color: "var(--st-prop)" }}
            onClick={() => dispatch({ type: "ADMIN_VIEW", view: "generate" })}>
            <p className="font-semibold flex items-center gap-1">
              <Dot tone="prop" blink />Proposal pending
            </p>
            <p className="text-faint mt-0.5">
              {app.diff.proposal.changes.length} changes · click to review
            </p>
          </div>
        )}

        <SideLabel>Configuration</SideLabel>
        {CONFIG_SECTIONS.map(s => (
          <NavItem key={s.v} icon={s.icon} label={s.label}
            disabled={!isDataLoaded}
            active={isDataLoaded && app.adminView === "config" && app.adminSection === s.v}
            onClick={isDataLoaded ? () => {
              dispatch({ type: "ADMIN_SECTION", section: s.v });
              dispatch({ type: "ADMIN_VIEW", view: "config" });
            } : undefined} />
        ))}

        {/* Reset — always accessible, sits below a divider */}
        <div className="mx-1.5 my-1 border-t" style={{ borderColor: "var(--grid-line)" }} />
        <NavItem icon="↺" label="Reset to empty"
          active={false}
          onClick={() => {
            if (window.confirm("Reset to empty state? All overrides and pins will be cleared.")) {
              dispatch({ type: "RESET" });
            }
          }} />
      </nav>
    </aside>
  );
}

/* ================================================================
   PAGE HEADER (shared — exported for leader/admin)
================================================================ */
function PageHeader({ title, subtitle, actions, tone }) {
  return (
    <div className="flex items-center gap-3 px-3 h-10 border-b border-bd bg-raised shrink-0"
      style={tone ? { borderBottomColor: TONES[tone].borderColor, background: TONES[tone].background } : {}}>
      <div className="min-w-0">
        <h1 className="text-xs font-semibold leading-tight">{title}</h1>
        {subtitle && <p className="text-2xs text-dim leading-tight truncate">{subtitle}</p>}
      </div>
      <div className="flex-1"></div>
      {actions && <div className="flex items-center gap-1.5">{actions}</div>}
    </div>
  );
}
window.PageHeader = PageHeader;

/* ================================================================
   EXPORT MODAL
================================================================ */
function ExportModal({ app, onClose }) {
  const firstEmp = SF.EMPLOYEES.length > 0 ? SF.EMPLOYEES[0].i : 0;
  const [scope, setScope] = useState("team");
  const [pick,  setPick]  = useState(firstEmp);

  return (
    <Modal title="Export / Print" onClose={onClose} width={400}
      footer={
        <React.Fragment>
          <Btn variant="ghost" onClick={onClose}>Cancel</Btn>
          <Btn onClick={() => {
            scope === "team"
              ? exportTeamCSV(app.overrides, app.weekOffset)
              : exportPersonCSV(pick, app.overrides);
            onClose();
          }}>↓ Download CSV</Btn>
          <Btn variant="primary" onClick={() => {
            printSchedule(app.overrides, app.weekOffset, scope === "person" ? pick : null);
            onClose();
          }}>⎙ Print / PDF</Btn>
        </React.Fragment>
      }>
      <div className="space-y-3 text-xs">
        <Seg value={scope} onChange={setScope} className="w-full"
          options={[
            { v: "team",   label: "Full team (current week)"    },
            { v: "person", label: "Single employee (4 weeks)"   },
          ]} />
        {scope === "person" && (
          <Field label="Employee">
            <SelectBox value={String(pick)} onChange={v => setPick(Number(v))} className="w-full"
              options={SF.EMPLOYEES.map(e => ({ v: String(e.i), label: e.name + " · " + e.deptName }))} />
          </Field>
        )}
        <div className="text-2xs text-dim leading-snug pt-0.5">
          CSV imports directly into Google Sheets or Excel.<br />
          PDF: browser print dialog → "Save as PDF".
        </div>
      </div>
    </Modal>
  );
}

/* ================================================================
   APP ROOT
================================================================ */
function App() {
  const [app, dispatch]   = useReducer(reducer, initialState);
  const [shortcuts,   setShortcuts]   = useState(false);
  const [exportModal, setExportModal] = useState(false);
  const [onboarding,  setOnboarding]  = useState(false);
  const saveTimer = useRef(null);

  /* ---- IndexedDB: load on mount ---- */
  useEffect(() => {
    DB.get("cw_state_v1").then(data => {
      dispatch({ type: "DB_LOAD", data: data || {} });
    }).catch(() => dispatch({ type: "DB_LOAD", data: {} }));
  }, []);

  /* ---- IndexedDB: autosave (debounced 800ms) ---- */
  useEffect(() => {
    if (!app.dbLoaded) return;
    clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(() => {
      DB.set("cw_state_v1", {
        dataMode:  app.dataMode,
        locale:    app.locale,
        overrides: DB.mapToObj(app.overrides),
      });
    }, 800);
    return () => clearTimeout(saveTimer.current);
  }, [app.dataMode, app.locale, app.overrides, app.dbLoaded]);

  /* ---- Keyboard shortcuts ---- */
  useEffect(() => {
    const onKey = e => {
      const tag = (e.target.tagName || "").toLowerCase();
      if (tag === "input" || tag === "select" || tag === "textarea" || e.metaKey || e.ctrlKey) return;
      if (e.key === "?")           { setShortcuts(v => !v); return; }
      if (e.key === "Escape")      { dispatch({ type: "SEED_OFF" }); return; }
      const k = e.key.toLowerCase();
      if      (k === "s")              dispatch({ type: "SEED_TOGGLE" });
      else if (k === "g")              dispatch({ type: "ADMIN_VIEW", view: "generate" });
      else if (k === "t")              dispatch({ type: "WEEK", set: 0 });
      else if (e.key === "ArrowLeft")  dispatch({ type: "WEEK", delta: -1 });
      else if (e.key === "ArrowRight") dispatch({ type: "WEEK", delta:  1 });
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, []);

  const violations = useMemo(() => {
    let n = 0;
    app.overrides.forEach(o => { if (o.viol && o.viol.length) n++; });
    return n;
  }, [app.overrides]);

  const edits          = app.overrides.size;
  const isDataLoaded   = app.dataMode !== "empty";
  const showEmptyBoard = !isDataLoaded;

  return (
    <div className="h-screen flex flex-col overflow-hidden">
      <div className="flex-1 flex overflow-hidden">
        <Sidebar app={app} dispatch={dispatch} isDataLoaded={isDataLoaded} />
        <div className="flex-1 flex flex-col min-w-0 overflow-hidden">
          {showEmptyBoard && !onboarding && <EmptyBoardState dispatch={dispatch} onSetupOrg={() => setOnboarding(true)} />}
          {showEmptyBoard &&  onboarding && <OnboardingWizard dispatch={dispatch} />}
          {!showEmptyBoard && <LeaderSurface app={app} dispatch={dispatch} onExport={() => setExportModal(true)} />}
        </div>
      </div>

      {/* Status bar */}
      <StatusBar
        left={
          <React.Fragment>
            <span className="flex items-center gap-1.5">
              <Dot tone="ok" />{app.dbLoaded ? "saved" : "loading…"}
            </span>
            {violations > 0 && (
              <span className="flex items-center gap-1 font-semibold" style={{ color: "var(--st-crit)" }}>
                ⚠ {violations} violated cell{violations > 1 ? "s" : ""}
              </span>
            )}
            {edits > 0 && <span>{edits} override{edits > 1 ? "s" : ""}</span>}
            {app.pins.size > 0 && <span>◢ {app.pins.size} pinned</span>}
          </React.Fragment>
        }
        right={
          <React.Fragment>
            {isDataLoaded && (
              <span className="font-mono">
                {SF.EMPLOYEES.length} staff · {SF.SHIFTS.length} shifts
              </span>
            )}
            <button type="button" className="hover:text-ink" onClick={() => setShortcuts(true)}>
              ? shortcuts
            </button>
          </React.Fragment>
        }
      />

      {/* Keyboard shortcuts modal */}
      {shortcuts && (
        <Modal title="Keyboard shortcuts" onClose={() => setShortcuts(false)} width={340}>
          <table className="w-full text-xs">
            <tbody>
              {[
                ["← →", "Previous / next week"],
                ["T",   "Go to current week"],
                ["S",   "Toggle seed mode"],
                ["G",   "Open generator"],
                ["Esc", "Exit seed mode"],
                ["?",   "This panel"],
              ].map(([k, d]) => (
                <tr key={k} className="border-b border-[var(--grid-line)] last:border-b-0">
                  <td className="py-1.5 w-24"><KeyHint>{k}</KeyHint></td>
                  <td className="py-1.5 text-dim">{d}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Modal>
      )}

      {exportModal && <ExportModal app={app} onClose={() => setExportModal(false)} />}
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(<App />);
